# Dependencies
# markdown:         redcarpet
# highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Baby Lizard
tagline:          'Documentation'
description:      'Baby Lizard software helps to create simulation components and visualize them. © SpaceServicesAustralia Pvt Ltd.'
url:              http://spaceservicesaustralia.com
baseurl:          '/BLD/'

author:
  name:           'Mohit Sharma'
  url:            https://twitter.com/spaceservices9

paginate:         5

# Custom vars
version:          0.1.0

